### ISSUE TITLE
B-9 Permanent building Labels

### ISSUE THREAD

**Issue by lara-tran** [ClaudiaLapalme/pikaroute#114]
**App commit hash**: 9114767181e71fced040c9e99d8b623489c771fb

**Context**
The building markers appear at any zoom level.

**Steps to Reproduce**

1. Move map to either Loyola or SGW campus

**Actual Behavior**
The building markers are displayed at any zoom level

![Screenshot_20200317-203830](https://user-images.githubusercontent.com/43098723/76914059-5726e400-688f-11ea-8df1-b72c9008a598.png)

**Expected behavior**
The building markers should only be displayed at a specific zoom level.

**Comment by Aleoris** [comment]
It is broken on mobile?
