### ISSUE TITLE
AT-1 As a user, I want the application to find my current location so that I can know my relative position on the map

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#130]
**Steps**
Given that I am on the home page,

**Expected Output**
then I should see a small blue icon representing my current position.

**Result**
Pass / Not Pass

**Comments**
Add a button to show my current location

**Comment by jodavimehran** [comment]
It doesn't work!

**Comment by ClaudiaLapalme** [comment]
Not sure what doesn’t work, it works on web, actual mobile phone, an emulator on our side.

**Comment by jodavimehran** [comment]
> Not sure what doesn’t work, it works on web, actual mobile phone, an emulator on our side.

I guess something is wrong with the version that I have.

**Comment by jodavimehran** [comment]
Accepted
