### ISSUE TITLE
AT-6 As a user, I want to get basic information on a building from the Concordia campuses when I click on it so that I am able to quickly get a lot of information on the building

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#131]
**Steps**
Given that I am on the home page,
And that I recenter the map on either of the two campuses,
And that I click on one of the highlighted buildings,

**Expected Output**
Then I should see a pop-up providing the name, picture, address, website, phone, and schedule (if available) of said building.

**Result**
Pass / Not Pass

**Comments**
Comments from the PO in regards to the test

**Comment by jodavimehran** [comment]
Accepted
