### ISSUE TITLE
AT-7 As a user, I want a search bar so that I can search for points of interests and see them on the map

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#132]
**Steps**
Given that I am on the home page,
And that I click on the search bar,
And that I enter _Starbucks_,
And that I confirm the location from a drop-down menu,

**Expected Output**
Then I should see the map recenter on the chosen location with a red marker on the location.

**Result**
Pass / Not Pass

**Comments**
Comments from the PO in regards to the test

**Comment by jodavimehran** [comment]
This feature only works for Hall Building classes like H805 or H807.
So It doesn't work for Concordia Building names or other search terms like restaurant, cafe.

**Comment by ClaudiaLapalme** [comment]
This feature is design to search for more precise things than « café », if you input « starbucks » or « mcdonald’s » you will be provides with a drop down of choices

**Comment by jodavimehran** [comment]
Accepted
