### ISSUE TITLE
AT-8 As a colourblind user, I want the application to use an adapted colour palette so that I can use the application properly

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#133]
**Steps**
Given that I am on the home page,
And that I click on the hamburger menu,
And that I click on settings,
And that I open the accessibility options,
And that I select the colourblind mode,

**Expected Output**
Then the application’s theme should go from burgundy to black

**Result**
Pass / Not Pass

**Comments**
Comments from the PO in regards to the test

**Comment by jodavimehran** [comment]
Accepted
