### ISSUE TITLE
AT-9 As a user, I want to see my outdoor route on a map so that I can reach my destination

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#134]
**Steps**
Given that I am on the routes page
And that I input a departure location,
And that I input a destination location,
And that I select one of the suggest routes,

**Expected Output**
Then I should see the route rendered on the map.

**Result**
Pass / Not Pass

**Comments**
Comments from the PO in regards to the test

**Comment by jodavimehran** [comment]
Accepted
