### ISSUE TITLE
AT-10 As a user, I want directions to outdoor points of interest so that I can reach my destination easily

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#135]
**Steps**
Given that I am on the routes page
And that I input a departure or destination location,

**Expected Output**
Then I should be provided with a drop down menu of points of interest that can be selected as departure or arrival locations

**Result**
Pass / Not Pass

**Comments**
Comments from the PO in regards to the test

**Comment by jodavimehran** [comment]
Accepted
