### ISSUE TITLE
AT-12 As a user, I want to obtain indoor directions to and from any room of H so that I can reach my destination easily

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#137]
**Steps**
Given that I am on the routes page
And that I input a departure location on the 8th or 9th floor,
And that I input a destination location on the 8th or 9th floor,

**Expected Output**
Then I should see the suggested paths to reach my destination

**Result**
Pass / Not Pass

**Comments**
Comments from the PO in regards to the test

**Comment by jodavimehran** [comment]
I can see the suggested paths but when I click on one of then nothing happens.

**Comment by ClaudiaLapalme** [comment]
This issue only pertains to generating the suggestions in the route page. Choosing an option and displaying it on the map is part of issue #74.

In the expected output, by "I should see the suggested paths to reach my destination," we mean the suggestions in the routes page. An image of the expected output has been included below as a reference:

![image](https://user-images.githubusercontent.com/32103530/78732302-49093800-7910-11ea-97b9-608865169866.png)

**Comment by jodavimehran** [comment]
Accepted
