### ISSUE TITLE
AT-13 As a user, I want to obtain suggestions of routes that include the Concordia Shuttle when appropriate so that I can take the best route to reach my destination

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#150]
**Steps**
Given that I am on the routes page
And that I input Hall Building as my departure location,
And that I input Loyola as my destination,
And that I select the Concordia University campus

**Expected Output**
Then I should see the Concordia shuttle included in the route suggestions

**Comment by jodavimehran** [comment]
Accepted
