### ISSUE TITLE
AT-15 As a physically disabled user, I want to obtain indoor directions that accomodate my disability so that I can reach my destination easily

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#152]
**Steps**
Given that I am on the routes page
And that I input H801 as my departure location,
And that I input H937 as my destination

**Expected Output**
Then I should see a wheelchair-friendly route included in the route suggestions

**Comment by jodavimehran** [comment]
Accepted
