### ISSUE TITLE
AT-16 As a user, I want to get written instructions on how to reach my destination so that I can reach it easily

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#156]
**Steps**
Given that I am on the routes page
And that I input Station Berri as my departure location,
And that I input Parc Jean-Drapeau as my destination,
And that I select the route option that uses the yellow line

**Expected Output**
Then I should see a drop-down menu with written instructions on how to reach my destination

**Result**
Pass / Not Pass

**Comment by jodavimehran** [comment]
Accepted
