### ISSUE TITLE
AT-17 As a user, I want to see my indoor route on a map so that I can reach my destination easily

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#157]
**Steps**
Given that I am on the routes page
And that I input H820 as my departure location,
And that I input H937 as my destination,
And that I select the first option from the suggestions

**Expected Output**
Then I should see the route to take traced on the map

**Result**
Pass / Not Pass

**Comment by jodavimehran** [comment]
Accepted
