### ISSUE TITLE
AT-18 As a user, I want to see the next event in my Google Calendar so that I can get a quick rundown about it

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#158]
**Steps**
Given that I am on the home page,
And that I have an upcoming event in my calendar
And that I log into my calendar on the application

**Expected Output**
Given that I am on the home page,And that I have an upcoming event in my calendarAnd that I log into my calendar on the applicationThen I should see my next event in the sidebar

**Result**
Pass / Not Pass

**Comment by ClaudiaLapalme** [comment]
Note: Departure Location is hardcoded at H801 for simplicity's sake

Note: If the location is not on the 8th or 9th floor, the routes page will open and you will have to manually input a departure and arrival location.

**Comment by jodavimehran** [comment]
Accepted
