### ISSUE TITLE
AT-19 As a user, I want to click on the next event in my Google Calendar to obtain directions so that I can reach my next event easily

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#159]
**Steps**
Given that I am on the routes page
And that my next event is a class at location H911
And that I click on Go to Event

**Expected Output**
Then the application should transition to the routes page and provide suggestions to reach my indoor destination

**Result**
Pass / Not Pass

**Comment by jodavimehran** [comment]
Accepted
