### ISSUE TITLE
AT-2 As a user, I want to toggle between the 8th and 9th floor of Hall building so that I can see the indoor floor plans of either

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#169]
**Steps**
Given that I am on the home page
and that the map is centered on the H building,
and that the map is zoomed in enough to see the floor plans,

**Expected Output**
Then I should be able to toggle between H8 and H9

**Result**
Pass / Not Pass

**Comment by jodavimehran** [comment]
Accepted
