### ISSUE TITLE
AT-3 As a user, I want the buildings of the Concordia campuses to be highlighted on the map so that I can distinguish them from the rest

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#170]
**Steps**
Given that I am on the home page,
and that the map is centered on either of the two Concordia campuses

**Expected Output**
Then I should see all of the buildings on that campus overlaid with a semi-opaque black polygon

**Result**
Pass / Not Pass

**Comment by jodavimehran** [comment]
Accepted
