### ISSUE TITLE
AT-4 As a user, I want to be able to toggle between both Concordia campuses on the map so that I can quickly access either

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#171]
**Steps**
Given that I am on the home page,
and that the map is placed arbitrarily,
and that the user has pressed on the campus toggle button,

**Expected Output**
Then I should see the map recenter itself on the selected campus

**Result**
Pass / Not Pass

**Comment by jodavimehran** [comment]
Accepted
