### ISSUE TITLE
AT-5 As a user, I want to obtain a variety of suggested routes so that I can choose the best route to reach my destination

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#172]
**Steps**
Given that I am on the directions page,
and that I enter my location,
and that I enter my destination,

**Expected Output**
Then I should receive a variety of walking, driving, cycling, and public transport options to reach m destination

**Result**
Pass / Not Pass

**Comment by jodavimehran** [comment]
Accepted
