### ISSUE TITLE
US-17 As a user, I want to see my outdoor route on a map so that I can reach my destination

### ISSUE THREAD

**Issue by ClaudiaLapalme** [ClaudiaLapalme/pikaroute#73]
The application should overlay the outdoor map shown with lines indicate the path a user must follow to reach their destination

Requirements
- [ ] The itinerary selected by the user should be overlaid on the map
- [ ] A button should be provided for users to go back to the home page

![Group 50](https://user-images.githubusercontent.com/32103530/75602736-cc27aa80-5a95-11ea-9bdf-834a610a1116.png)
![Group 49](https://user-images.githubusercontent.com/32103530/75602737-ccc04100-5a95-11ea-99a8-2faea590f571.png)

**Comment by david-ron** [comment]
@ClaudiaLapalme  Should the UI also be part of this task or just the rendering of the map? Based on the description its just the rendering from what I understand

**Comment by ClaudiaLapalme** [comment]
@david-ron this should only be putting the line on the map, not the top-nav, that’s the written instructions story

**Comment by david-ron** [comment]
@ClaudiaLapalme Okay thank you
