### ISSUE TITLE
Bug Report Template

### ISSUE THREAD

**Issue by aiceball** [ClaudiaLapalme/pikaroute#79]
**App commit hash**: <insert hash here>

**Context**
A little bit of context in what flow the bug has occured (i.e. while looking for directions at midnight, nothing was found)

**Steps to Reproduce**

1. step 1
2. step N

**Actual Behavior**
What it does

**Expected behavior**
What is expected to be done

**Comment by ClaudiaLapalme** [comment]
Closed to remove clutter from backlog. Pinned for future reference.
